name: " Bug Report"
description: Create a new ticket for a bug.
title: " [BUG] - <title>"
labels: [
  "bug"
]
body:
  - type: dropdown
    id: severity
    attributes:
      label: "Severity"
      description: Severity of the issue
      options:
        -  Severe
        -  Critical
        -  Error
        -  Performance
        -  Cosmetic

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      description: Priority
      options:
        - High
        - Medium
        - Low    
  - type: dropdown
    id: browsers
    attributes:
      label: "Browsers"
      description: What browsers are you seeing the problem on ?
      multiple: true
      options:
        - Firefox (Default)
        - Chrome
        - Safari
        - Microsoft Edge
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: "OS"
      description: What is the impacted environment ?
      options:
        - Ubuntu 22.04 (Default)
        - Windows
        - macOS
    validations:
      required: false 
  - type: textarea
    id: additionl
    attributes:
      label: "Additional Environment Details "
      description: 
      placeholder: Any additional Environment Details
    validations:
      required: false      
  - type: textarea
    id: description
    attributes:
      label: "Current Behaviour"
      description: Please enter an explicit description of your issue
      placeholder: A concise Description of what you are experiencing 
    validations:
      required: false
  - type: input
    id: reprod-url
    attributes:
      label: "Reproduction URL"
      description: Please enter your GitHub URL to provide a reproduction of the issue
      placeholder: ex. https://github.com/USERNAME/REPO-NAME
    validations:
    
  - type: textarea
    id: description2
    attributes:
      label: "Expected Behaviour"
      description: Please enter an explicit description of your issue
      placeholder: A concise Description of what you expected to happen
    validations:
      required: false    
  
  - type: textarea
    id: reprod
    attributes:
      label: "Reproduction steps"
      description: Please enter an explicit description of your issue
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
      render: bash
    validations:
      required: false
  - type: textarea
    id: screenshot
    attributes:
      label: "Screenshots/Logs"
      description: If applicable, add screenshots to help explain your problem.
      value: |
        ![DESCRIPTION](LINK.png)
    validations:
      required: false

   
